image: node

stages:
  - build
  - deploy

build-lib:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - README.md
      - LICENSE
      - package.json

publish:
  image: node:alpine
  stage: deploy
  dependencies:
    - build-lib
  only:
    - tags
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --access=public
